require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'client' do
  config = use_native_modules!
  permissions_path = '../node_modules/react-native-permissions/ios'

  use_react_native!(:path => config["reactNativePath"])

  # pod 'RNSiriWaveView', :path => '../node_modules/react-native-siri-wave-view'

  pod 'ReactNativeAudioToolkit', :path => '../node_modules/@react-native-community/audio-toolkit'

  pod 'GoogleSignIn', '~> 5.0.0'

  pod 'react-native-branch', path: '../node_modules/react-native-branch'

  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone"

  target 'clientTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper' => '0.87.0', 'Flipper-Folly' => '2.5.3', 'Flipper-RSocket' => '1.3.1' })
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'client-tvOS' do
  # Pods for client-tvOS

  target 'client-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
